language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t brunofurlan/docker-course -f Dockerfile.dev .

script:
  - docker run -e CI=true brunofurlan/docker-course npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-course"
  env: "DockerCourse-env"
  bucket_name: "elasticbeanstalk-sa-east-1-584538479119"
  bucket_path: "docker-course"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY